version: '3'
services:
  school-database:
    image: postgres
    container_name: 'school-database'
    restart: 'always'
    environment:
      POSTGRES_USER: school-alf
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db-alf
    volumes:
      - db-volumes:/var/lib/postgresql/data
  school-api:
    image: 'giuliarruda/challenge-school:latest'
    build:
      context: .
    container_name: 'school-api'
    restart: 'always'
    ports:
      - "8080:8080"
    depends_on:
      - school-database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://school-database:5432/db-alf
      SPRING_DATASOURCE_USERNAME: school-alf
      SPRING_DATASOURCE_PASSWORD: root
volumes:
  db-volumes: