api:
  version: v1
  prefix: api
spring:
  profiles:
    active: dev

# Swagger properties configuration
spring-doc:
  api-docs:
    enabled: true
  use-fqn: false
  swagger-ui:
    path: /docs
    tags-sorter: alpha
    operations-sorter: method
